MB-37898: Rebuild folly with CXX_STD=c++17
When attempting to build CB Servr with C++17, two issues related to Folly are encountered, requiring modification of the Folly cbdep:

1. On macOS there are linker errors when attempting to link a program
   built with -std=c++17 and libfolly.a built with -std=c++14:

    Undefined symbols for architecture x86_64:
      "folly::SharedMutexImpl<false, void, std::__1::atomic, false, false>::kPrevDefer", referenced from:
      ...
      "folly::SharedMutexImpl<false, void, std::__1::atomic, false, false>::kWaitingNotS", referenced from:
      ...
      "folly::SharedMutexImpl<false, void, std::__1::atomic, false, false>::kMaxSpinCount", referenced from:

These symbols are defined in the folly source (SharedMutex.h) as:

    static constexpr uint32_t kPrevDefer = 1 << 8;

It would seem that under C++14 no definition of this symbol is
included in libfolly.a:

    nm -C libfolly.a|grep "folly::SharedMutexImpl<false, void, std::__1::atomic, false, false>::kPrevDefer"
    <EOF>

However when the application is built as C++17 is _does_ expect a
symbol definition to be present.

To actually get a definition, rebuild folly with C++17.

2. However, as a consequence of rebuilding with C++17, there are some
   changes to the linking requirements of Folly (the exact reason I
   don't understand!) - Folly with C++17 requires linking against
   additional libraries which in _theory_ it always needed (they are
   neeed at Folly's own compile-time) but previously when built for
   C++14 we didn't need to link when using folly.

As an example, OpenSSLUtils.cpp.o now gets included by the linker when
linking against libfolly.a, even when the linking program doesn't use
any symbols from OpenSSLUtils.cpp.o. Given OpenSSLUtils.cpp.o itself
uses OpenSSL, this means that programs linking Folly (and not
otherwise linking OpenSSL) give errors like:

   Linking CXX executable platform-atomic_duration-test
    /usr/bin/ld: ../../../tlm/deps/folly.exploded/lib/libfolly.a(OpenSSLUtils.cpp.o): undefined reference to symbol 'SSL_get_fd@@OPENSSL_1_1_0'

This affects a number of objects in libfolly.a. Essentially the
previously benign "missing" dependancies of Folly (Boost::filesystem,
Boost::program_options, Boost::regex, gflags and OpenSSL) cause linker
failures.

Fix by adding these to the FOLLY_LIBRAIRES variable - i.e. Folly and
all its dependencies.

Also tweak the definition of FOLLY_INCLUDE_DIR so it doesn't keep
growing, appending hte same paths every time CMake is run.

Change-Id: I0be2d5e7f19cb0e85d41c67e44ffeeba524a9178
Reviewed-on: http://review.couchbase.org/122608
Reviewed-by: James Harrison <james.harrison@couchbase.com>
Tested-by: Build Bot <build@couchbase.com>
Reviewed-by: Jim Walker <jim@couchbase.com>