MB-51718: MSVC: Disable legacy offsetof behaviour
When trying to upgrade folly to v2022.02.14.00, a curious error
message is seen under MSVC:

    folly.exploded\include\folly/Synchronized.h(1414): error C2131: expression did not evaluate to a constant
    folly.exploded\include\folly/Synchronized.h(1414): note: failure was caused by non-constant arguments or reference to a non-constant symbol
    folly.exploded\include\folly/Synchronized.h(1414): note: see usage of 'folly::Synchronized<Foo::State,std::mutex>::Simulacrum::mutex_'
    folly.exploded\include\folly/Synchronized.h(1410): note: while compiling class template member function 'SynchronizedType *folly::LockedPtr<SynchronizedType,folly::SynchronizedBase<folly::Synchronized<Foo::State,std::mutex>,folly::detail::SynchronizedMutexLevel::Unique>::LockPolicyExclusive>::parent(void) const'
            with
            [
                SynchronizedType=folly::Synchronized<Foo::State,std::mutex>
            ]
    folly.exploded\include\folly/Synchronized.h(1266): note: see reference to function template instantiation 'SynchronizedType *folly::LockedPtr<SynchronizedType,folly::SynchronizedBase<folly::Synchronized<Foo::State,std::mutex>,folly::detail::SynchronizedMutexLevel::Unique>::LockPolicyExclusive>::parent(void) const' being compiled
            with
            [
                SynchronizedType=folly::Synchronized<Foo::State,std::mutex>
            ]
    C:\Users\daver\repos\folly_syncho_test\folly_syncho_test.cpp(6): note: see reference to class template instantiation 'folly::LockedPtr<Subclass,folly::SynchronizedBase<Subclass,folly::detail::SynchronizedMutexLevel::Unique>::LockPolicyExclusive>' being compiled
            with
            [
                Subclass=folly::Synchronized<Foo::State,std::mutex>
            ]

This was reproduced in the following minimal example:

    #include <folly/Synchronized.h>
    #include <mutex>

    struct Foo {
        int getDatum() {
            auto locked = state.lock();
            return locked->datum;
        }

        struct State {
            int datum;
        };
        folly::Synchronized<State, std::mutex> state;
    };

    int main() {
            Foo foo;
            return foo.getDatum();
    }

Interstingly, attempting to reproduce the issue outside our build
environment (i.e. an empty MSVC 2017 project) did not exhibit the
error.

Comparing any compiler flags which are different in the CB Server
CMake setup, it was found that removing the extra flag "/Zc:offsetof-"
fixed the issue. This flag was added as part of adding support for
MSVC 2017 (e21739f8), where we needed to enable legacy, non-confirming
behaviour for 'offsetof' via the flag "/Zc:offsetof-" for forestdb.

Remove this flag - forestdb no longer requires it.

Change-Id: Id4f27be704c04b81b9a6613e64ba562618009553
Reviewed-on: https://review.couchbase.org/c/tlm/+/175277
Tested-by: Build Bot <build@couchbase.com>
Reviewed-by: Richard de Mellow <richard.demellow@couchbase.com>