MB-30040: Link libdl with folly where needed
Folly requires symbol dlsym. On platforms which have the dynamic
library functions in a separate library from the C runtime, this means
Folly depends on libdl - for example on Ubuntu 18.04:

    /usr/bin/ld: tlm/deps/folly.exploded/lib/libfollytsan.a(CacheLocality.cpp.o): undefined reference to symbol 'dlsym@@GLIBC_2.2.5'

Fix by adding libdl to the set of libraries folly requires, where
applicable.

Change-Id: Ie9f58bee9bf9398fe3835705c72d33c6e4113de8
Reviewed-on: http://review.couchbase.org/107368
Reviewed-by: Trond Norbye <trond.norbye@couchbase.com>
Tested-by: Build Bot <build@couchbase.com>