Forcefully set CMAKE_OSX_DEPLOYMENT_TARGET
Forcefully set this so existing CMake build/CMakeCache.txt files are
updated to the correct version, otherwise developers when updating to
code which use macOS 10.15 specific features will get (confusing)
build failures such as:

    In file included from /Users/dave/repos/couchbase/server/source/kv_engine/cluster_framework/cluster.cc:11:
    /Users/dave/repos/couchbase/server/source/kv_engine/cluster_framework/cluster.h:145:36: error: 'path' is unavailable: introduced in macOS 10.15
                const std::filesystem::path& path,
                                       ^

Change-Id: I926802594e701d5b0774defd3e094f529df8f902
Reviewed-on: https://review.couchbase.org/c/tlm/+/175886
Tested-by: Build Bot <build@couchbase.com>
Reviewed-by: James H <james.harrison@couchbase.com>