Revert "MB-41209: cbdeps: Update to Folly v2020.08.24.00"
This reverts commit 674a448f66d020644f4d52bf82b3ba5cd83a4710.

Reason for revert: Fails on MSVC 2017:

    build\tlm\deps\folly.exploded\include\folly/portability/IOVec.h(28): warning C4005: 'IOV_MAX': macro redefinition
    platform\include\platform/platform_socket.h(43): note: see previous definition of 'IOV_MAX'
    build\tlm\deps\folly.exploded\include\folly/portability/IOVec.h(30): error C2011: 'iovec': 'struct' type redefinition
    platform\include\platform/platform_socket.h(38): note: see declaration of 'iovec'
    build\tlm\deps\folly.exploded\include\folly/net/NetOps.h(104): error C2371: 'sa_family_t': redefinition; different basic types
    platform\include\platform/socket.h(32): note: see declaration of 'sa_family_t'
    build\tlm\deps\folly.exploded\include\folly/net/NetOps.h(118): error C2011: 'msghdr': 'struct' type redefinition
    platform\include\platform/platform_socket.h(45): note: see declaration of 'msghdr'
    build\tlm\deps\folly.exploded\include\folly/net/NetOps.h(129): error C2079: 'mmsghdr::msg_hdr' uses undefined struct 'msghdr'
    build\tlm\deps\folly.exploded\include\folly/io/async/EventBaseBackendBase.h(36): error C2079: 'folly::EventReadCallback::IoVec::data_' uses undefined struct 'iovec'
    build\tlm\deps\folly.exploded\include\folly/io/async/EventBaseBackendBase.h(54): error C2079: 'folly::EventRecvmsgCallback::MsgHdr::data_' uses undefined struct 'msghdr'

Not clear why this passed on the CV job (which _did_ include all
kv_engine CV jobs...)

Change-Id: I5778d8088b0f03d19caacf0c0afb1e70131a4a29
Reviewed-on: http://review.couchbase.org/c/tlm/+/135871
Tested-by: Dave Rigby <daver@couchbase.com>
Reviewed-by: Dave Rigby <daver@couchbase.com>