Revert "CBD-6605, remove pyopenssl and cryptography from cbpy's dependency list."
This reverts commit ca109136def7b9cb892f070add28afb723f3f208.

couchbase-cli still depends on cryptography and pyopenssl
getting errors such as
File "/opt/couchbase/lib/python/couchbase-cli", line 10, in <module>
  import cbmgr
  File "/opt/couchbase/lib/python/cbmgr.py", line 26, in <module>
    from cluster_manager import ClusterManager
  File "/opt/couchbase/lib/python/cluster_manager.py", line 21, in <module>
    from x509_adapter import X509Adapter, X509AdapterFactory
  File "/opt/couchbase/lib/python/x509_adapter.py", line 31, in <module>
    from cryptography.exceptions import UnsupportedAlgorithm
ModuleNotFoundError: No module named 'cryptography'

-Ming

Change-Id: I22eac70d8b9936286d1b5d28a6adff13cd0f1704
Reviewed-on: https://review.couchbase.org/c/tlm/+/242605
Tested-by: Ming Ho <ming.ho@couchbase.com>
Reviewed-by: Neil Huang <neil.huang@couchbase.com>