MB-41209: cbdeps: rollback Folly to v2019.08.12.00
The new version of Folly (v2020.03.05.00) causes Windows EE build to
fail:

    C:\Jenkins\workspace\couchbase-server-windows\build\tlm\deps\glog.exploded\include\glog/log_severity.h(51):
    fatal error C1189: #error: ERROR macro is defined. Define
    GLOG_NO_ABBREVIATED_SEVERITIES before including logging.h. See the
    document for detail.

Rolling back to previous version while this is investigated.

Change-Id: I6894b994d9829381281e062d82f76c6eceb173f9
Reviewed-on: http://review.couchbase.org/c/tlm/+/135443
Tested-by: Build Bot <build@couchbase.com>
Reviewed-by: Dave Rigby <daver@couchbase.com>