Revert "MB-41209: cbdeps: Re-apply: Update Folly to v2020.03.05.00"
This reverts commit f981f55e7a1014459a5ebf285cf865f5496910f3.

Reason for revert: issue with boost / folly headers for 
ASan build:

Compile error at [2020-09-08T06:27:50.870Z] tlm/deps/folly.exploded/include/folly/functional/Invoke.h:22:10: fatal error: boost/preprocessor/control/expr_iif.hpp: No such file or directory 

Change-Id: Idc063a9085a630ff0b91c47c36b9a2702aaa8ed2
Reviewed-on: http://review.couchbase.org/c/tlm/+/135749
Tested-by: Dave Rigby <daver@couchbase.com>
Reviewed-by: Dave Rigby <daver@couchbase.com>