MB-50108: Go: Don't override CC for macOS with sanitizers
On macOS, Golang fails with the following error when building with TSan:

    _cgo_export.c:3:10: fatal error 'stdlib.h' file not found

This appears to be caused by our override of CC to be CMAKE_C_COMPILER
(which is 'cc' by default). Using Golang's default of 'clang' works
correctly, even though they are the same binary:

    ‡ md5sum /usr/bin/cc /usr/bin/clang
    bc8c7b268c169441f6889ca04d4d836a  /usr/bin/cc
    bc8c7b268c169441f6889ca04d4d836a  /usr/bin/clang

I can only assume that the name they are launched under affects
default include paths...

Change-Id: I31872703279764e2f85c592f82aa729d4a8f4060
Reviewed-on: https://review.couchbase.org/c/tlm/+/167654
Tested-by: Dave Rigby <daver@couchbase.com>
Tested-by: Build Bot <build@couchbase.com>
Reviewed-by: Trond Norbye <trond.norbye@couchbase.com>