Revert "MB-37898: Remove gflags from folly (and build)"
This reverts commit be059d32aaacc6b3a0b0849365e25b911792d0d5.

The patch cause CV for kv to fail with:

15:09:11 [ 75%] Linking CXX executable ../../../ep-engine_ep_unit_tests
15:09:30 ../CMakeFiles/ep_objs.dir/src/durability/active_durability_monitor.cc.o: In function `WaitOptions':
15:09:30 /home/couchbase/jenkins/workspace/kv_engine-clang_analyzer-master/build/tlm/deps/folly.exploded/include/folly/synchronization/WaitOptions.h:30: undefined reference to `folly::WaitOptions::Defaults::spin_max'
15:09:33 clang: error: linker command failed with exit code 1 (use -v to see invocation)

Change-Id: I91585bf22c97751c8ebf019f3008f2c88da480e5
Reviewed-on: http://review.couchbase.org/123033
Tested-by: Build Bot <build@couchbase.com>
Reviewed-by: Trond Norbye <trond.norbye@couchbase.com>