MB-41209: Glog: Define GLOG_NO_ABBREVIATED_SEVERITIES
When compiling with Folly v2020.03.05.00 or newer on Windows, compiler
errors are seen a Folly header which includes glog/logging.h is used:

    build\tlm\deps\glog.exploded\include\glog/log_severity.h(51):
    fatal error C1189:
    #error:  ERROR macro is defined. Define GLOG_NO_ABBREVIATED_SEVERITIES before including logging.h. See the document for detail.

This is doucmented in the google log docs[1], WinDGI.h (via Windows.h)
defines a macro which collides with one defined by glog.

The documentation suggests two ways to fix this:

1. Disable glog's abbeviated severity levels by defining
   GLOG_NO_ABBREVIATED_SEVERITIES.

2. Disable the definition of ERROR - which can be done by defining
   WIN32_LEAN_AND_MEAN.

(2) has the advantage of also cutting a load of Windows.h content
which we don't use (for example various graphical things), so commit
5055c6b ("MB-41209: Define WIN32_LEAN_AND_MEAN under MSVC") did
exactly that.

However, it turns out the documentation is incorrect - under VS 2017
at least WIN32_LEAN_AND_MEAN doesn't affect if WinGDI.h is included
via Windows.h.

As such, this patch chooses option (1) - define
GLOG_NO_ABBREVIATED_SEVERITIES which _does_ fix the issue.

[1]: http://rpg.ifi.uzh.ch/docs/glog.html

Change-Id: Ia8845c68484ae602ae616f5f484849d6cd5475d1
Reviewed-on: http://review.couchbase.org/c/tlm/+/135690
Tested-by: Build Bot <build@couchbase.com>
Reviewed-by: James Harrison <james.harrison@couchbase.com>