MB-58743: [MSVC] add /bigobj
Failing to build unit tests on windows due to:

    kv_engine\engines\ep\tests\module_tests\dcp_stream_test.cc :
       fatal error C1128: number of sections exceeded objecti
       file format limit: compile with /bigobj

This commit cherry-picks 6ab5d641ad5c57f2ef50a1db582a402bd53cb5f5.

Change-Id: If1016ded511c1fd185fbd015fb155c3861112d1a
Reviewed-on: https://review.couchbase.org/c/tlm/+/201436
Reviewed-by: Trond Norbye <trond.norbye@couchbase.com>
Well-Formed: Restriction Checker
Tested-by: Build Bot <build@couchbase.com>