MB-41209: cbdeps: Re-apply: Update Folly to v2020.03.05.00
This patch previously (602a104) broke the Windows EE build:

    C:\Jenkins\workspace\couchbase-server-windows\build\tlm\deps\glog.exploded\include\glog/log_severity.h(51):
    fatal error C1189: #error: ERROR macro is defined. Define
    GLOG_NO_ABBREVIATED_SEVERITIES before including logging.h. See the
    document for detail.

This was due to a conflict between google-log and Windows headers
both trying to #define an 'ERROR' macro.

This has been addressed by stopping Glog from defining that macro
via e754404
("MB-41209: Glog: Define GLOG_NO_ABBREVIATED_SEVERITIES") and hence
we can re-upgrade Folly to v2020.03.05.00.

Change-Id: I5c419df3b4d43e08cf7cddb3c152c97f2c4ca278
Reviewed-on: http://review.couchbase.org/c/tlm/+/135444
Tested-by: Build Bot <build@couchbase.com>
Reviewed-by: Trond Norbye <trond.norbye@couchbase.com>