MB-58743: [MSVC] add /bigobj
Failing to build unit tests on windows due to:

    kv_engine\engines\ep\tests\module_tests\dcp_stream_test.cc :
       fatal error C1128: number of sections exceeded objecti
       file format limit: compile with /bigobj

Change-Id: I79b7a33c381997926dcf10802db68eee95b50568
Reviewed-on: https://review.couchbase.org/c/tlm/+/197389
Reviewed-by: Chris Hillery <ceej@couchbase.com>
Tested-by: Build Bot <build@couchbase.com>